language: python
python:
  - "2.7"
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
install: 
  - cd varnorm
  - python setup.py install
  - cd ..
#  - pip install -r requirements.txt
  - pip install flask
  - pip install pymongo
  - pip install pygr
  - pip install coveralls
services:
  - mongodb
script: 
# command to run coveralls (test coverage) and run tests
#  - coverage run --source=flaskr flaskr/test_flaskr.py
  - coverage run --source=flaskr -m unittest discover 
#  - python -m unittest discover
#  - python flaskr/test_flaskr.py
after_success:
  coveralls

notifications:
  travis encrypt "rpfb:MmlTuZjFJMyZ8FlLvzaPL2El" --add notifications.slack
