language: python
python:
  - "2.7"
# command to install dependencies
#install: "pip install -r requirements.txt"
install: "pip install flask"
install: "pip install coveralls"
# command to run coveralls (test coverage) and run tests
script: 
  - coverage run --source=flaskr 
  - python flaskr/test_flaskr.py
after_success:
  coveralls

